fix(hooks): update useBoard to dispatch action in setTimeout
This prevents a race condition with Redux reducer:

```
Error: You may not call store.getState() while the reducer is executing.
The reducer has already received the state as an argument. Pass it down
from the top reducer instead of reading it from the store.
```