test(jest): fix test errors
```
ReferenceError: TextEncoder is not defined
```

https://reactrouter.com/upgrading/v6

```
react-router-dom Cannot destructure property 'basename' of
'React10.useContext(...)' as it is null.
```